// scripts/prepare-deploy.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const outputDir = path.join(rootDir, '.output');
const publicDir = path.join(outputDir, 'public');
const serverDir = path.join(outputDir, 'server');

// 1. Prepare Frontend: Generate .htaccess for public_html
const htaccessContent = `
# Generated by Nuxt Deployment Script
<IfModule mod_rewrite.c>
    RewriteEngine On
    # Serve existing static files directly
    RewriteCond %{REQUEST_URI} !^/app/ 
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
</IfModule>
`;

console.log('ℹ️  Creating .htaccess...');
fs.writeFileSync(path.join(publicDir, '.htaccess'), htaccessContent.trim());

// 2. Prepare Backend: Create a clean staging folder
const deployBackendDir = path.join(rootDir, '.deploy-backend');
if (fs.existsSync(deployBackendDir)) fs.rmSync(deployBackendDir, { recursive: true, force: true });
fs.mkdirSync(deployBackendDir);

// 3. Create the CJS Wrapper (index.js)
// This sits at the root of your app folder on the server
const indexJsContent = `
const path = require('path');
const port = process.env.PORT || 3000;
process.env.NITRO_PORT = port;
process.env.NITRO_HOST = '0.0.0.0';

(async () => {
  try {
    // Points to the code inside the .output folder
    const serverPath = path.join(__dirname, '.output', 'server', 'index.mjs');
    await import(serverPath);
    console.log('Nuxt Bridge: Server started on port ' + port);
  } catch (error) {
    console.error('Nuxt Bridge Error:', error);
    process.exit(1);
  }
})();
`;
fs.writeFileSync(path.join(deployBackendDir, 'index.js'), indexJsContent.trim());

// 4. Copy package.json
// We extract this from the build output so cPanel knows what to install
const buildPackageJsonPath = path.join(serverDir, 'package.json');
if (fs.existsSync(buildPackageJsonPath)) {
    fs.copyFileSync(buildPackageJsonPath, path.join(deployBackendDir, 'package.json'));
    console.log('ℹ️  package.json ready for Hosting NPM Install.');
} else {
    console.warn('⚠️  No package.json found in output. Ensure preset is node-server.');
}

// 5. Copy Application Code (EXCLUDING node_modules)
console.log('ℹ️  Copying server code (skipping node_modules)...');

const destNitroDir = path.join(deployBackendDir, '.output', 'server');
fs.mkdirSync(destNitroDir, { recursive: true });

// Recursive copy with filter to strict ignore node_modules
fs.cpSync(serverDir, destNitroDir, { 
    recursive: true,
    filter: (source) => {
        // If the path contains 'node_modules', return false to skip it
        return !source.includes('node_modules');
    }
});

console.log('✅ Preparation complete.');
console.log(`   Frontend: ${publicDir}`);
console.log(`   Backend:  ${deployBackendDir} (Lightweight - No node_modules)`);