// scripts/prepare-deploy.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const outputDir = path.join(rootDir, '.output');
const publicDir = path.join(outputDir, 'public');
const serverDir = path.join(outputDir, 'server');

// 1. Generate the .htaccess for public_html
// This handles static files correctly and passes the rest to the Node app
const htaccessContent = `
# Generated by Nuxt Deployment Script
<IfModule mod_rewrite.c>
    RewriteEngine On
    
    # 1. Serve existing static files directly (Images, JS, CSS)
    RewriteCond %{REQUEST_URI} !^/app/ 
    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]

    # 2. Let the Hosting Environment handle the proxy to Node
    # The hosting tool typically appends its own logic below or uses Passenger
    # If your hosting overwrites this file, we might need to adjust, 
    # but usually, they respect rules at the top.
</IfModule>
`;

console.log('ℹ️  Creating .htaccess...');
fs.writeFileSync(path.join(publicDir, '.htaccess'), htaccessContent.trim());


// 2. Create the CJS Wrapper (index.js) inside the server folder
// We place it in .output/server so we can upload the whole folder cleanly
const indexJsContent = `
const path = require('path');

// Bridge CommonJS to Nuxt ESM
const port = process.env.PORT || 3000;
process.env.NITRO_PORT = port;
process.env.NITRO_HOST = '0.0.0.0';

(async () => {
  try {
    // Import the actual Nuxt server
    // Note: relative path assumes this index.js sits in ~/app/ and .output is inside ~/app/
    const serverPath = path.join(__dirname, '.output', 'server', 'index.mjs');
    await import(serverPath);
    console.log('Nuxt Bridge: Server started on port ' + port);
  } catch (error) {
    console.error('Nuxt Bridge Error:', error);
    process.exit(1);
  }
})();
`;

console.log('ℹ️  Creating CJS Entry wrapper (index.js)...');
// We write this to a temporary deploy folder to keep structure clean
const deployServerDir = path.join(rootDir, '.deploy-server');
if (fs.existsSync(deployServerDir)) fs.rmSync(deployServerDir, { recursive: true, force: true });
fs.mkdirSync(deployServerDir);

// Write index.js to the deploy root
fs.writeFileSync(path.join(deployServerDir, 'index.js'), indexJsContent.trim());

// 3. Move package.json to the deploy root
// Hosting needs package.json at ~/app/package.json to detect dependencies
console.log('ℹ️  Moving package.json...');
if (fs.existsSync(path.join(serverDir, 'package.json'))) {
    fs.copyFileSync(
        path.join(serverDir, 'package.json'),
        path.join(deployServerDir, 'package.json')
    );
}

// 4. Copy the actual .output/server folder into the deploy structure
// Result: ~/app/.output/server
console.log('ℹ️  Structuring server files...');
const destNitroDir = path.join(deployServerDir, '.output', 'server');
fs.mkdirSync(path.dirname(destNitroDir), { recursive: true });

// Helper to copy directory recursively
fs.cpSync(serverDir, destNitroDir, { recursive: true });

console.log('✅ Preparation complete.');
console.log(`   Frontend ready at: ${publicDir}`);
console.log(`   Backend ready at:  ${deployServerDir}`);