# Sample workflow for building and deploying a Nuxt site to GitHub Pages
#
# To get started with Nuxt see: https://nuxtjs.org/docs/get-started/installation
#
name: Build Nuxt

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi
      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            .nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-          
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      - name: Build Nuxt app
        run: ${{ steps.detect-package-manager.outputs.manager }} run build

  # Deployment job
  # deploy:
  #   - name: FTP Deploy Action via lftp (FTP, SFTP, FTPS)
  #     # You may pin to the exact commit or the version.
  #     # uses: pontago/lftp-deploy-action@47debd112419af76b6b7c0ee7861dc506a26f01b
  #     uses: pontago/lftp-deploy-action@v1.0.1
  #     with:
  #       # Sever Hostname or IP
  #       host: # default is 
  #       # Login Username
  #       username: # default is 
  #       # Login Password
  #       password: # optional, default is 
  #       # Default port are FTP(21), SFTP(22).
  #       port: # optional, default is 
  #       # Transfer protocol (ftp, ftps, sftp)
  #       protocol: # optional, default is ftp
  #       # If you want to use SSH Private Key, protocol parameter should be sftp.
  #       ssh_private_key: # optional, default is 
  #       # If you want to no SSL verification, false. (FTPS)
  #       verify_cert: # optional, default is true
  #       # Upload source directory.
  #       local_dir: # optional, default is 
  #       # Upload remote directory.
  #       remote_dir: # optional, default is 
  #       # If doesn't exists, create remote directory.
  #       create_remote_dir: # optional, default is true
  #       # Support lftp commands. If you input local_dir and remote_dir, the script will be executed after mirror command.
  #       script: # optional, default is 
  #       # You can check the operation. Not upload and create remote directory.
  #       dry_run: # optional
  #       # Debug mode. Output lftp log and upload verbose.
  #       debug: # optional
  #       # Timeout in seconds.
  #       timeout: # optional, default is 30
  #       # Max retries. 0 is unlimited. 1 means no retries.
  #       max_retries: # optional, default is 5
